### ISSUE TITLE
Concepts: Document cognition documentation needed

### ISSUE THREAD

**Issue by accakks** [yellowmessenger/documentation#16]
@Shree06-patel Please assign this issue to @RakYM07 

In documentation>concepts>Bot knowledge

- [x] I've created a PR to add docs for FAQ list section #15 
- [x] **The remaining part is the knowledge from documents**

**Comment by Shree06-patel** [comment]
sure, will work on adding the docs

**Comment by Shree06-patel** [comment]
assigning the doc cog documentation to @RakYM07
